# Generated by Django 5.2 on 2025-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('map', models.CharField(max_length=255)),
                ('history', models.TextField()),
                ('geography', models.TextField()),
                ('holidays', models.TextField()),
                ('travel', models.TextField()),
            ],
        ),
    ]
